<?php //netteCache[01]000388a:2:{s:4:"time";s:21:"0.16281200 1364943334";s:9:"callbacks";a:2:{i:0;a:3:{i:0;a:2:{i:0;s:19:"Nette\Caching\Cache";i:1;s:9:"checkFile";}i:1;s:66:"/Users/Tomik/Projects/PHP/fraphpuccino/app/templates/@layout.latte";i:2;i:1364943304;}i:1;a:3:{i:0;a:2:{i:0;s:19:"Nette\Caching\Cache";i:1;s:10:"checkConst";}i:1;s:25:"Nette\Framework::REVISION";i:2;s:30:"c0332ac released on 2013-03-08";}}}?><?php

// source file: /Users/Tomik/Projects/PHP/fraphpuccino/app/templates/@layout.latte

?><?php
// prolog Nette\Latte\Macros\CoreMacros
list($_l, $_g) = Nette\Latte\Macros\CoreMacros::initRuntime($template, 'hig0slycds')
;
// prolog Nette\Latte\Macros\UIMacros

// snippets support
if (!empty($_control->snippetMode)) {
	return Nette\Latte\Macros\UIMacros::renderSnippets($_control, $_l, get_defined_vars());
}

//
// main template
//
?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="author" content="Tomáš Vítek, http://tomasvitek.com" />

	<title><?php ob_start(); Nette\Latte\Macros\UIMacros::callBlock($_l, 'title', $template->getParameters()); echo $template->trim($template->striptags(ob_get_clean())) ?></title>

	<link rel="stylesheet" type="text/css" href="<?php echo htmlSpecialChars($baseUrl) ?>/css/styles.css" />
</head>
<body>
    <div id="content">
    	<h1><a href="http://github.com/tomikvitek/fraphpuccino"><img src="<?php echo htmlSpecialChars($baseUrl) ?>/img/fraphpuccino.png" /></a></h1>
<?php Nette\Latte\Macros\UIMacros::callBlock($_l, 'content', $template->getParameters()) ?>
    	<footer>
			Generated by <a href="http://github.com/tomikvitek/fraphpuccino">fraphpuccino</a>.
		</footer>
    </div>
</body>
</html>